name: E2E Test
on:
  pull_request:
    branches:
      - "**"

jobs:
  e2e_visual_regression:
    name: e2e_visual_regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install npm
        run: |
          npm install -g npm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd frontend-nuxt
          npm install

      - name: Build Application
        run: |
          cd frontend-nuxt
          npm build

      - name: Start Application
        run: |
          cd frontend-nuxt
          npm start &
        env:
          PORT: 3000

      - name: Wait for Application to Start
        run: |
          while ! nc -z localhost 3000; do   
            sleep 1
          done

      - name: Run Cypress with Chromatic for E2E Tests
        run: ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 npx chromatic --cypress --project-token="chpt_2ad3ebaa4a0c9df" --exit-zero-on-changes
