name: Visual Regression Test
on:
  pull_request:
    branches:
      - "**"

jobs:
  component_visual_regression:
    name: component_visual_regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install npm
        run: |
          npm install -g npm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd frontend-nuxt
          npm install

      - name: Build Application
        run: |
          cd frontend-nuxt
          npm build

      - name: Build Storybook
        run: |
          cd frontend-nuxt
          npm build-storybook

      - name: Run Chromatic for Component Visual Regression
        uses: chromaui/action@latest
        with:
          projectToken: "chpt_2ad3ebaa4a0c9df"
